export const options = [
    {
        "createdBy": 1,
        "group": "userRoles",
        "isActive": true,
        "isDefault": false,
        "label": "Admin",
        "value": "admin",
    },
    {
        "createdBy": 1,
        "group": "embroideryTypes",
        "isActive": true,
        "isDefault": false,
        "label": "Applique",
        "value": "applique",
    },
    {
        "createdBy": 1,
        "group": "currency",
        "isActive": true,
        "isDefault": false,
        "label": "Botswana Pula",
        "value": "BWP",
    },
    {
        "createdBy": 1,
        "group": "embroideryTypes",
        "isActive": true,
        "isDefault": false,
        "label": "Cap",
        "value": "cap",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Cap Back",
        "value": "capBack",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Cap Front",
        "value": "capFront",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Cap Left Side",
        "value": "capLeftSide",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Cap Right Side",
        "value": "capRightSide",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": true,
        "label": "Embroidery",
        "value": "embroidery",
    },
    {
        "createdBy": 1,
        "group": "embroideryTypes",
        "isActive": true,
        "isDefault": true,
        "label": "Flat",
        "value": "flat",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": true,
        "label": "Front Left",
        "value": "frontLeft",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Front Right",
        "value": "frontRight",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": false,
        "label": "Golf Shirts",
        "value": "golfShirts",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Left Sleeve",
        "value": "leftSleeve",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Lower Back",
        "value": "LowerBack",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": false,
        "label": "Masks",
        "value": "masks",
    },
    {
        "createdBy": 1,
        "group": "embroideryTypes",
        "isActive": true,
        "isDefault": false,
        "label": "Name Tag",
        "value": "nameTag",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": false,
        "label": "Needles",
        "value": "needles",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": false,
        "label": "Prewound Bobbins",
        "value": "prewoundBobbins",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Right Sleeve",
        "value": "rightSleeve",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": false,
        "label": "Round Necks",
        "value": "roundNeck",
    },
    {
        "createdBy": 1,
        "group": "userRoles",
        "isActive": true,
        "isDefault": false,
        "label": "Sales",
        "value": "sales",
    },
    {
        "createdBy": 1,
        "group": "currency",
        "isActive": true,
        "isDefault": false,
        "label": "South African Rand",
        "value": "ZAR",
    },
    {
        "createdBy": 1,
        "group": "productCategories",
        "isActive": true,
        "isDefault": false,
        "label": "Threads",
        "value": "threads",
    },
    {
        "createdBy": 1,
        "group": "currency",
        "isActive": true,
        "isDefault": true,
        "label": "United States Dollar",
        "value": "USD",
    },
    {
        "createdBy": 1,
        "group": "embroideryPositions",
        "isActive": true,
        "isDefault": false,
        "label": "Upper Back",
        "value": "UpperBack",
    },
    {
        "createdBy": 1,
        "group": "userRoles",
        "isActive": true,
        "isDefault": true,
        "label": "User",
        "value": "user",
    },
    {
        "createdBy": 1,
        "group": "currency",
        "isActive": true,
        "isDefault": false,
        "label": "Zimbabwean Bond",
        "value": "ZWB",
    },
    {
        "createdBy": 1,
        "group": "currency",
        "isActive": true,
        "isDefault": false,
        "label": "Zimbabwean Rtgs",
        "value": "ZWR",
    }
]